sudo: required
language: ruby

services:
  - docker
  
env:
  - IMAGE=ubuntu/trusty32
  - IMAGE=ubuntu/trusty64
  - IMAGE=ubuntu/precise32
  - IMAGE=ubuntu/precise64
  - IMAGE=hashicorp/precise32
  - IMAGE=hashicorp/precise64

install:
  # for virtualbox
  - sudo add-apt-repository multiverse
  # for vagrant
  - sudo sed 's/utopic/vivid/g' -i /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get -y install build-essential linux-headers-`uname -r` dkms
  - sudo apt-get -y install virtualbox virtualbox-dkms
  - VBoxManage -v
  - sudo apt-get -y install vagrant
  - vagrant -v

script:
  - egrep '(vmx|svm)' /proc/cpuinfo
  - vagrant init ${IMAGE}
  - vagrant up
  - vagrant ssh-config
  - netstat -lan
