sudo: required
language: ruby

services:
  - docker
  
env:
  - IMAGE=ubuntu/trusty32
  - IMAGE=ubuntu/trusty64
  - IMAGE=ubuntu/precise32
  - IMAGE=ubuntu/precise64
  - IMAGE=hashicorp/precise32
  - IMAGE=hashicorp/precise64

install:
  - sudo echo "deb http://download.virtualbox.org/virtualbox/debian precise contrib" | sudo tee -a /etc/apt/sources.list
  - wget http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -y install build-essential linux-headers-`uname -r` dkms
  - sudo apt-get -y install virtualbox virtualbox-dkms
  - VBoxManage -v
  - sudo wget -nv https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4_x86_64.deb
  - sudo dpkg -i vagrant_1.7.4_x86_64.deb
  - vagrant -v

script:
  # http://askubuntu.com/a/41554
  - egrep '(vmx|svm)' /proc/cpuinfo || echo $?
  - vagrant init ${IMAGE}
  - vagrant up
  - vagrant ssh-config
  - netstat -lan
